{{--
    Printable supplier return note, mirroring resources/views/receipts/_body.blade.php:
    table/inline-block only (dompdf doesn't support flexbox/grid).

    Expects: $settings (ReceiptSetting) and $supplierReturn (SupplierReturn,
    with items.product, supplier, creator eager-loaded).
--}}
<div style="width: 480px; margin: 16px auto; font-family: {{ $settings->font_family }}; font-size: 13px; color: #1A2420;">
    <div style="text-align: center; margin-bottom: 8px;">
        <div style="font-weight: 700; font-size: 16px;">{{ $settings->shop_name }}</div>
        @if ($settings->address)<div style="font-size: 12px;">{{ $settings->address }}</div>@endif
        @if ($settings->phone)<div style="font-size: 12px;">Tel: {{ $settings->phone }}</div>@endif
    </div>

    <hr style="border-top: 1px dashed #999;">

    <div style="text-align: center; font-weight: 700; font-size: 15px; margin: 8px 0;">
        SUPPLIER RETURN NOTE #{{ $supplierReturn->id }}
    </div>

    <table style="width: 100%; font-size: 12px; border-collapse: collapse;">
        <tr><td>Supplier</td><td style="text-align: right;">{{ $supplierReturn->supplier->name }}</td></tr>
        <tr><td>Return Date</td><td style="text-align: right;">{{ $supplierReturn->return_date->format('Y-m-d') }}</td></tr>
        <tr><td>Prepared By</td><td style="text-align: right;">{{ $supplierReturn->creator->name }}</td></tr>
        <tr><td>Status</td><td style="text-align: right;">{{ ucfirst($supplierReturn->status) }}</td></tr>
    </table>

    <hr style="border-top: 1px dashed #999;">

    <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
        <thead>
            <tr style="border-bottom: 1px solid #999;">
                <th style="text-align: left; padding-bottom: 3px;">Product</th>
                <th style="text-align: right; padding-bottom: 3px;">Qty</th>
                <th style="text-align: right; padding-bottom: 3px;">Reason</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($supplierReturn->items as $item)
                <tr>
                    <td style="padding: 2px 0;">{{ $item->product->name }}</td>
                    <td style="padding: 2px 0; text-align: right;">{{ $item->quantity }}</td>
                    <td style="padding: 2px 0; text-align: right;">{{ ucfirst(str_replace('_', ' ', $item->reason)) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <hr style="border-top: 1px dashed #999;">

    <table style="width: 100%; font-size: 12px; border-collapse: collapse;">
        <tr><td>Resolution</td><td style="text-align: right;">{{ ucfirst($supplierReturn->resolution) }}</td></tr>
        <tr style="font-weight: 700;"><td>Credit Note Value</td><td style="text-align: right;">{{ number_format($supplierReturn->credit_note_value, 2) }}</td></tr>
    </table>

    <hr style="border-top: 1px dashed #999;">

    <div style="text-align: center; font-size: 11px; color: #666;">
        Generated by {{ $settings->shop_name }} POS
    </div>
</div>
